name: Front Workflow

on: push

jobs:
  run-github-actions:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v3
      - name: List Files
        run: ls
      - name: directory location
        run: pwd
        
      - name: Get the output time
        run: echo"${{ steps.hello.outputs.time }}"
